### ISSUE TITLE
Substream

### ISSUE THREAD

**Issue by cognitom** [e-jigsaw/gulp-riot#27]
Is it possible to turn "compiling process" into substream?
Related https://github.com/muut/riotjs/issues/381 I'm thinking about possibility to take  "compiling process" away from Riot.js. At this moment, Riot.js has an external API only for JavaScript compiler, but now it's extending to CSS. How about? Any feedback is welcome. Thanks.

``` javascript
// THIS IS PSEUDO CODE (NOT WORK)
var gulp         = require('gulp')
var riot         = require('gulp-riot')
var jade         = require('gulp-jade')
var coffee       = require('gulp-coffee')
var less         = require('gulp-less')
var autoprefixer = require('gulp-autoprefixer')
var uglify       = require('gulp-uglify')

gulp.task('riot', function(){
  gulp.src('example.tag')
  .pipe(riot({
    html:   function(src){ src.pipe(jade()) }
    script: function(src){ src.pipe(coffee()) }
    style:  function(src){ src.pipe(less())
                              .pipe(autoprefixer()) }
  }))
  .pipe(uglify())
  .pipe(gulp.dest('dest'))
})
```

**Comment by e-jigsaw** [comment]
`gulp-riot` is JUST gulp plugin. Plugin should follow compiler behavior. So if riot compiler can take function that return stream as parameter then I will patch this plugin for there feature.

BTW I agree with take "pre-compiling process" away from riot compiler. My experimental work [roister](https://github.com/e-jigsaw/roister) is same idea. I thought this approach is good because we can use pre-compile language and do not modify original riot compiler. But riot compiler now supports that languages. So I finished this work.

Related javascript framework Vue-component's compiler [vue-component-compiler](https://github.com/vuejs/vue-component-compiler) has same implement(see https://github.com/vuejs/vue-component-compiler/tree/master/compilers). And it uses [insert-css](https://github.com/substack/insert-css) in multiple `<style>` problem.

`insert-css` needs browserify or webpack or something similar tool. It is bad for simple gulp users... So I using Webpack when I use vue-component-compiler(see https://github.com/e-jigsaw/emo-vue).

伝わりましたかね？？英語微妙だとおもうんで、不明点あれば指摘していただけると...!この件、なんとかしたさあるので早く決着つけたいですね

**Comment by cognitom** [comment]
@e-jigsaw  Thanks for quick feedback. https://github.com/vuejs/vue-component-compiler/blob/master/index.js seems a good starting point! :)

I think the best way to solve this problem is...
- Riot.js has complete APIs about compiling
- Riot.js has an official compiling helper (like roister)
- [gulp-riot](https://github.com/e-jigsaw/gulp-riot), [riotify](https://github.com/jhthorsen/riotify) and [riotjs-loader](https://github.com/esnunes/riotjs-loader) support the APIs

How do you think...? @tipiirai

**Comment by tipiirai** [comment]
argh... so much information here to digest. Could you narrow down the question? And perhaps post an issue to Riot issue tracker. Thank you!

**Comment by cognitom** [comment]
@tipiirai Sorry, I'll post an issue later. Thanks!
